name: Contributions

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]
  issue_comment:
    types: [created]
  schedule:
    - cron: '30 5 * * *'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  contributions:
    uses: hotcodepush-team/.github/.github/workflows/contributions.yml@main
